//
// Copyright 2017 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#ifndef USDRAYSENSORIMAGING_API_H
#define USDRAYSENSORIMAGING_API_H

#include "pxr/base/arch/export.h"

#if defined(PXR_STATIC)
#   define USDRAYSENSORIMAGING_API
#   define USDRAYSENSORIMAGING_API_TEMPLATE_CLASS(...)
#   define USDRAYSENSORIMAGING_API_TEMPLATE_STRUCT(...)
#   define USDRAYSENSORIMAGING_LOCAL
#else
#   if defined(USDRAYSENSORIMAGING_EXPORTS)
#       define USDRAYSENSORIMAGING_API ARCH_EXPORT
#       define USDRAYSENSORIMAGING_API_TEMPLATE_CLASS(...) ARCH_EXPORT_TEMPLATE(class, __VA_ARGS__)
#       define USDRAYSENSORIMAGING_API_TEMPLATE_STRUCT(...) ARCH_EXPORT_TEMPLATE(struct, __VA_ARGS__)
#   else
#       define USDRAYSENSORIMAGING_API ARCH_IMPORT
#       define USDRAYSENSORIMAGING_API_TEMPLATE_CLASS(...) ARCH_IMPORT_TEMPLATE(class, __VA_ARGS__)
#       define USDRAYSENSORIMAGING_API_TEMPLATE_STRUCT(...) ARCH_IMPORT_TEMPLATE(struct, __VA_ARGS__)
#   endif
#   define USDRAYSENSORIMAGING_LOCAL ARCH_HIDDEN
#endif

#endif
